# Databricks notebook source
# MAGIC %run ../utils/mount_storage

# COMMAND ----------

refined_base_path = "/mnt/dlpssa/refined" #dbutils.secrets.get("demo", "refined-datalake-path") + "cu"
curated_base_path = "/mnt/dlpssa/curated" #dbutils.secrets.get("demo", "refined-datalake-path") + "cu_curated"
refined_format = "delta"
curated_format = "delta"

adls_mount(account_name="dlpssa4dev04", container="raw", mnt_pnt="/mnt/dlpssa/raw")
adls_mount(account_name="dlpssa4dev04", container="refined", mnt_pnt="/mnt/dlpssa/refined")    
adls_mount(account_name="dlpssa4dev04", container="curated", mnt_pnt="/mnt/dlpssa/curated")

# COMMAND ----------

def create_database(db_name, path, drop=False):
    if drop:
        spark.sql(f"DROP DATABASE IF EXISTS {db_name} CASCADE;")    
    spark.sql(f"CREATE DATABASE IF NOT EXISTS {db_name} LOCATION '{path}'")

    
create_database("refined", refined_base_path, False)
create_database("curated", curated_base_path, False)

# COMMAND ----------

# MAGIC %sql
# MAGIC SHOW CREATE TABLE refined.current;

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS curated.dim_area;
# MAGIC 
# MAGIC CREATE TABLE curated.dim_area (
# MAGIC dim_area_id bigint GENERATED BY DEFAULT AS IDENTITY,
# MAGIC area_code string,
# MAGIC area_name string,
# MAGIC display_level bigint,
# MAGIC is_deleted boolean,
# MAGIC last_modified timestamp
# MAGIC )
# MAGIC USING delta TBLPROPERTIES ('Type' = 'MANAGED', 'delta.enableChangeDataFeed' = 'true');

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS curated.dim_series;
# MAGIC 
# MAGIC CREATE TABLE curated.dim_series (
# MAGIC dim_series_id bigint GENERATED BY DEFAULT AS IDENTITY,
# MAGIC series_id STRING,
# MAGIC area_code STRING,   
# MAGIC item_code STRING,   
# MAGIC seasonal STRING,   
# MAGIC periodicity_code STRING,   
# MAGIC base_code STRING,   
# MAGIC base_period STRING,   
# MAGIC series_title STRING,  
# MAGIC begin_year BIGINT,   
# MAGIC begin_period STRING,   
# MAGIC end_year BIGINT,   
# MAGIC end_period STRING,   
# MAGIC is_deleted BOOLEAN,
# MAGIC last_modified timestamp
# MAGIC ) 
# MAGIC USING delta TBLPROPERTIES ('Type' = 'MANAGED', 'delta.enableChangeDataFeed' = 'true');

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS curated.dim_item;
# MAGIC 
# MAGIC CREATE TABLE curated.dim_item (
# MAGIC dim_item_id bigint GENERATED BY DEFAULT AS IDENTITY,
# MAGIC item_code STRING,
# MAGIC item_name STRING,
# MAGIC display_level BIGINT,
# MAGIC sort_sequence BIGINT,
# MAGIC is_deleted BOOLEAN,
# MAGIC last_modified timestamp
# MAGIC )
# MAGIC USING delta TBLPROPERTIES ('Type' = 'MANAGED', 'delta.enableChangeDataFeed' = 'true');

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS curated.fact_current;
# MAGIC 
# MAGIC CREATE TABLE curated.fact_current (
# MAGIC dim_series_id BIGINT,
# MAGIC dim_area_id BIGINT,
# MAGIC dim_item_id BIGINT,
# MAGIC year BIGINT,   
# MAGIC period STRING,   
# MAGIC value DOUBLE,
# MAGIC is_deleted BOOLEAN,
# MAGIC last_modified timestamp
# MAGIC )
# MAGIC USING delta TBLPROPERTIES ('Type' = 'MANAGED', 'delta.enableChangeDataFeed' = 'true');

# COMMAND ----------


